' Sequence
@startuml{sequence.png}
title Sequence
hide footbox

actor  "Alice or Carol" as Alice
actor  "Bob" as Bob
participant  "From" as From <<Client>>
participant  "To" as To<<Client>>
participant "PGP" as PGP <<PGP>> <<Component>>
participant "IPFS" as IPFS <<IPFS>><<Component>>
participant "Identity" as Identity <<Ethereum>><<Component>>
participant "Token" as Token <<Ethereum>><<Component>>

Alice -> From : From
Bob -> To : To
To  -> PGP : Generating Key
note left
Key: Public Key
end note
To  -> PGP : Export key
ref over PGP : PGP
To -> IPFS : Add Key
From -> IPFS : Get Key
ref over IPFS : IPFS
From -> PGP : Generating Key
From -> PGP : Import key
ref over PGP : PGP


From -> Identity : Identity
To -> Identity : Identity
ref over Identity : ERC725

From -> PGP : Edit key　Trust Key
ref over PGP : PGP
From -> Identity : ClaimVerifier
To -> Identity : ClaimVerifier
ref over Identity : ERC735

From -> PGP : Encrypt File
note left
File: academic and Professional
credential, research data
end note
ref over PGP : PGP
From -> IPFS : Add Encrypted File
ref over IPFS : IPFS
From -> Token : Token
To -> Token : Token
ref over Token : ERC20
From -> Token : NFTToken
To -> Token : NFTToken
ref over Token : ERC721
To -> IPFS : Get Encrypted File
ref over IPFS : IPFS
To -> PGP : Decrypt Encrypted File
ref over PGP : PGP
@enduml